### ISSUE TITLE
Tab resetting.

### ISSUE THREAD

**Issue by coquelin77** [SiLab-Bonn/testbeam_analysis#111] opened 2018-04-23 21:07 UTC
upon an error the tab resets, this prevents knowing exactly what caused the code to fail. i recommend no resetting it and letting the user change it. if there is a reset button this would work for the times when its more messed up

**Comment by leloup314** [comment] 2018-04-23 21:49
You should have access to the traceback of the error which caused the crash in the exceptions window before the tab is reset. This info should be sufficient in order to find out the cause, right?

**Comment by leloup314** [comment] 2018-04-24 14:21
I added this to the list of enhancements in #63 so I'm closing this . Feel free to add stuff to the list.

**Closed as completed by leloup314** 2018-04-24 14:21 UTC
Labels: gui
