### ISSUE TITLE
High memory consumption in track_finding

### ISSUE THREAD

**Issue by leloup314** [SiLab-Bonn/testbeam_analysis#102] opened 2018-02-19 17:58 UTC
When running the monopix analysis [script](https://github.com/SiLab-Bonn/testbeam_analysis/blob/monopix/testbeam_analysis/examples/monopix_efficiency.py) up to and including the `track_finding` step of the analysis, the memory consumption of `track_finding` reaches up to ~12 GB.

![figure_1](https://user-images.githubusercontent.com/18701435/36390721-4be72ff4-15a4-11e8-8800-7051dc1d2dde.png)
The figure above shows the memory consumption of the process ID connected to the analysis and the total memory consumption. I guess due to the multiprocessing, the memory peak on the right (~12 GB) is not assigned to the analysis PID, but clearly belongs to it (see figure below).

This effect can be avoided by setting `n_cores=1` in [`find_tracks`](https://github.com/SiLab-Bonn/testbeam_analysis/blob/development/testbeam_analysis/track_analysis.py#L127) (see figure below)
![figure_2](https://user-images.githubusercontent.com/18701435/36390725-4e96fad6-15a4-11e8-99d4-e86219ebf90a.png)

This was observed on:
- Ubuntu 16.04 (no programms running in background except 3 shells)
- Up-to-date `conda` environment with all packages from [here](https://github.com/SiLab-Bonn/pyBAR/wiki/Step-by-step-Installation-Guide)

Even though the run with `n_cores` set to 1 uses less memory, both runs take almost the same amount of time. The same results are obtained for `plot=False`( see below)

![figure_3](https://user-images.githubusercontent.com/18701435/36395800-515724a0-15bb-11e8-882e-35011f685cd4.png)
![figure_4](https://user-images.githubusercontent.com/18701435/36395805-57e7c8ba-15bb-11e8-9ee2-992e1d133cc4.png)

**Comment by leloup314** [comment] 2018-02-22 20:03
Possible bug in [line 182](https://github.com/SiLab-Bonn/testbeam_analysis/blob/development/testbeam_analysis/tools/smc.py#L182) of SMC: `chunk_size` of main process is given to every child process, causing every child process to consume the memory which the main process would use without multiprocessing. Possible solution is to set `chunk_size=int(self.chunk_size/self.n_cores)` in  [line 182](https://github.com/SiLab-Bonn/testbeam_analysis/blob/development/testbeam_analysis/tools/smc.py#L182) which distributes the total `chunk_size` of the main process among its children.
This then looks like this:
![figure_process_chunks_chunksize_by_n_cores](https://user-images.githubusercontent.com/18701435/36561280-9849839e-1813-11e8-85c9-47a0a144b3b2.png)
The black curve shows overall memory consumption of main process.

**Comment by DavidLP** [comment] 2018-02-23 12:11
The weird thing is that >> 1 Gb RAM is used per core in track finding since one chunk is only chunk_size * Track candidate size ~ 1000000 * 270 Bytes = 270 Mb. You have to memory profile per line to understand the underlying issue. I would not say that the issue is in SMC, since also the RAM per core is too high. Chunk size is meant per core, although that is not clear from the parameter description, that could be enhanced.

**Comment by leloup314** [comment] 2018-02-23 14:22
I managed to get a per line profiling:
[track_finding_profile.txt](https://github.com/SiLab-Bonn/testbeam_analysis/files/1751951/track_finding_profile.txt)

**Comment by leloup314** [comment] 2018-02-23 14:24
I managed to get a per line profiling:
[track_finding_profile.txt](https://github.com/SiLab-Bonn/testbeam_analysis/files/1751957/track_finding_profile.txt)

**Comment by DavidLP** [comment] 2018-02-23 14:38
Guess one also need to include `smc.py` in the profiling

**Comment by DavidLP** [comment] 2018-04-23 17:34
I also has troubles with track finding to exceed my 16 Gb of RAM. I reduced the chunk size to `100000` and RAM was constant at 4.4 Gb. So I guess that is a solution for now, although I am surprised of the overall memory consumption.

**Comment by leloup314** [comment] 2018-04-23 20:17
I guess `chunk_size=int(self.chunk_size/self.n_cores)` would be a more generic tmp. solution instead of having a static `chunk_size`. This would produce approx 4.4 Gb RAM usage independently of `n_cores`, right?

**Comment by DavidLP** [comment] 2018-04-23 20:24
Yes, that would be better

**Comment by DavidLP** [comment] 2018-05-25 16:57
Should be fixed now

**Closed as completed by DavidLP** 2018-05-25 16:57 UTC
Labels: bug
